# Generated by Django 3.0.3 on 2020-06-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='duration',
        ),
    ]
