# Generated by Django 3.0.3 on 2020-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0002_remove_userexercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='duration',
            field=models.IntegerField(blank=True, db_column='duration', null=True),
        ),
    ]
